global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'host.docker.internal:8000'  # API Gateway
        - 'host.docker.internal:8080'  # Auth Service
        - 'host.docker.internal:8081'  # Book Service
        - 'host.docker.internal:8082'  # User Service
        - 'host.docker.internal:8083'  # Borrowing Service
        - 'host.docker.internal:8084'  # Notification Service
        - 'host.docker.internal:8085'  # Saga Orchestrator
        - 'host.docker.internal:8761'  # Service Discovery
        - 'host.docker.internal:8888'  # Config Server
        labels:
          application: 'library-management-system'
